### ISSUE TITLE
Game (API) data is not displaying. 

### ISSUE THREAD

**Issue by Ediomojose** [mosh-hamedani/game-hub#15]
The game data are not displaying and it is throwing an error of network error. I attached a screenshot of this issue.
![Macbook-Air-game-hub-phi vercel app](https://github.com/user-attachments/assets/a7418fd9-3ce6-4526-8236-abdaa6ccfadb)

**Comment by nida-ullah** [comment]
get your api key from rawg.io and replace with the key in src/services/api-clients.ts

**Comment by Turmoil-IV** [comment]
rawg.io api no longer works.

You can find an alternative game API, but you'll have to adapt to align with what Mr. Mosh is doing. (like parameter names and so on) It's good practice. 
I personally used Giantbomb API. (enable CORS blocker Chrome extension for it to work in your development environment)

**Comment by Ediomojose** [comment]
Thank you
