### ISSUE TITLE
Platform selection 'Playstation' does not work

### ISSUE THREAD

**Issue by birgit2704** [mosh-hamedani/game-hub#5]
Hi Mosh,
thank you for this fantastic course!

I have one issue: the platform selection 'PlayStation' does not work. 
I cloned your repository and tried your version, but it does not work either.
All other platforms work fine. 

Can you please help?
Kind regards, 
Birgit

**Comment by StephenBrough** [comment]
Fixed in part 2. Change `platforms` in the query params to `parent_platforms`.

**Comment by birgit2704** [comment]
Ok. Thank you!
